version: "3.9"

services:
  app:
    build: .
    container_name: prisma_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/employees?schema=public"
    volumes:
      - .:/app
    command: npm start

  db:
    image: postgres:15
    container_name: prisma_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employees
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
